backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/img"
public_folder: "/img"

collections:
  - name: "journal" # Used in routes, e.g., /admin/collections/blog
    label: "Journal" # Used in the UI
    folder: "content/posts/journal" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Layout",
          name: "layout",
          widget: "string",
          default: "default",
        }
      - { label: "Refer", name: "refer", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - sortableFields: ["title", "date", "draft"]
