backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/img"
public_folder: "/img"

collections:
  - name: "journal" # Used in routes, e.g., /admin/collections/blog
    label: "Journal" # Used in the UI
    folder: "content/posts/journal" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sub-title",
          name: "subtitle",
          widget: "text",
          required: false,
        }
      - {
          label: "Abstract",
          name: "abstract",
          widget: "text",
          required: false,
        }

      - {
          label: "Layout",
          name: "layout",
          widget: "list",
          default: ["default", "image"],
          required: false,
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          default: "",
          required: false,
        }
      - { label: "Refer", name: "refer", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
